### PR TITLE
chore: Update node-version-12.20.1

### PR DESCRIPTION
**Pull request by ppmacmillan**
[CARD](https://rentpath.atlassian.net/browse/DX-479)
modify dockerfile to update node version

### CODE REVIEW

**Review by CraigCottingham — APPROVED** [review]

**Review by kaborso — APPROVED** [review]

**Comment by kaborso** [comment]
@tadjohnston @lfender6445 would it be cool to up the `yarn` version here as well? https://github.com/yarnpkg/yarn/blob/master/CHANGELOG.md#12210-and-prior

**Comment by tadjohnston** [comment]
@kaborso upgrading yarn would be great! We will also need to change the following in both ag and rent:

**Review by tadjohnston — APPROVED** [review]

**Comment by ppmacmillan** [comment]
@tadjohnston ok thanks noted ..

**Comment by lfender6445** [comment]
we would want

NODE_VERSION=14.15.4 YARN_VERSION=1.22.5

although its unclear to me if this is the correct docker base - a new one was created for the nextjs projects so this change may never get used

ill do some more research and circle back

**Comment by ppmacmillan** [comment]
Closing; see [Jira](https://rentpath.atlassian.net/browse/DX-479) comments.

**Pull request closed without merging**
